export const START_ENTITIES_FETCHING = 'START_ENTITIES_FETCHING';
export const STOP_ENTITIES_FETCHING = 'STOP_ENTITIES_FETCHING';

export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIES_FAILED = 'FETCH_ENTITIES_FAILED';

export const SAVE_ENTITY = 'SAVE_ENTITY';
export const SAVE_ENTITY_SUCCESS = 'SAVE_ENTITY_SUCCESS';
export const SAVE_ENTITY_FAILED = 'SAVE_ENTITY_FAILED';

export const DELETE_ENTITY = 'DELETE_ENTITY';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAILED = 'DELETE_ENTITY_FAILED';
